
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://diyclassics.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)


baseurl: /ams

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Patrick J. Burns"
title: "AMS Landing Page | SCS 2017"
description: "Official landing page for Ancient MakerSpaces: Digital Tools for Classics Scholarship, a workshop featured at the 2017 Annual Meeting of the Society for Classical Studies"
keywords: "digital humanities"
#favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: 1 # Set False for infinite loop, or set any number for finite loop.
type-speed: 5
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
#  - text: "Ancient MakerSpaces"
  - text: "Digital Tools for Classical Scholarship"

#me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
#vkontakte-share: True

disqus-shortname: "diyclassics"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/paper.png"
    date: "8:30-9:00am"
    description: "Paper: T. Beasley 'Visualizing Networks in the Ancient Mediterranean'"
  - image: "/img/timeline/workshop.png"
    date: "9:10-9:50am"
    description: "Workshop: R. Ast 'Digital Corpus of Literary Papyri'"
  - image: "/img/timeline/workshop.png"
    date: "9:55-10:45am"
    description: "Workshop: R. Benefiel 'Ancient Graffiti Project'"
  - image: "/img/timeline/workshop.png"
    date: "10:50-11:35am"
    description: "Workshop: S. Heath 'Make Your Own 3D Models'"
  - image: "/img/timeline/workshop.png"
    date: "11:40-12:25am"
    description: "Workshop: R. Horne 'Make Your Own Map'"
  - image: "/img/timeline/paper.png"
    date: "12:30-1:00pm"
    description: "Paper: P. Chaudhuri & J. Dexter 'Phylogenetic profiling and the reception of classical drama'"
  - image: "/img/timeline/workshop.png"
    date: "1:10-1:55pm"
    description: "Workshop: J. Gawley 'Intertext Mining With Tesserae'"
  - image: "/img/timeline/workshop.png"
    date: "2:00-2:45pm"
    description: "Workshop: B. Almas 'Perseids: Infrastructure for Research and Collaboration'"
  - image: "/img/timeline/panel.png"
    date: "3:00-4:00pm"
    description: "Panel: 'State of Digital Classics'"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "patrick@diyclassics.org"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/diyclassics"
  - title: "github"
    url: "https://diyclassics.github.io/ams/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: 
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  #Blog: 'latest-post'
  Schedule: 'timeline'
  #Schedule: 'schedule'
  #Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
